name: Check and Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check and bump version
        id: bump
        uses: jianlins/check_bump_version@v1
        with:
          bump-type: 'patch'
          prefix: 'pub_'
          current-version: '0.0.1'
      - name: Create release with bumped version
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.bump.outputs.version }}
          name: ${{ steps.bump.outputs.version }}
          draft: false
          prerelease: false
      - name: Use bumped version
        run: echo "Bumped version is ${{ steps.bump.outputs.version }}"
